### ISSUE TITLE
Use a proper license

### ISSUE THREAD

**Issue by shymega** [mlugg/C-_3D_Engine#1]
What you say in the README could be better expressed as saying that "this 3D engine is under the public domain", and put that in the file `LICENSE` in the root directory of the repo..

[This](https://creativecommons.org/publicdomain/zero/1.0/) might be a good public domain license to use.

Alternatively, as you said you want credit, why not use [CC BY](https://creativecommons.org/licenses/by/4.0/)? This allows people to share, adapt and even use your work commerically, but they *must* give you attribution.

Your current "license" at the moment is inadequate. Ideally, you need to choose a **proper** license.

**Comment by mlugg** [comment]
Will do soon.

**Comment by shymega** [comment]
@mlugg, no offence, but you don't close issues when it's _not_ fixed.

I propose you reopen this, and close it when the change has been made.

**Comment by silversquirl** [comment]
Just sticking this here... http://www.wtfpl.net/

**Comment by shymega** [comment]
@vktec I don't endorse that license, and neither does the FSF. It's not a good license. See [here][fsf] for details.

[fsf]: https://www.gnu.org/licenses/license-list.en.html#WTFPL

**Comment by silversquirl** [comment]
> See here for details.

*Looks*

> We do not recommend this license.

*No other details*

Umm... care to elaborate?
